import assert from 'node:assert/strict';
const store = new Map();
globalThis.localStorage = { getItem: key => store.get(key) ?? null, setItem: (key, value) => store.set(key, String(value)), removeItem: key => store.delete(key) };
const { STORAGE_KEYS } = await import('../src/database/schema.js?v=20260804-06');
const { getItem, setItem } = await import('../src/services/storage.service.js?v=20260804-06');
const { createBackup, restoreBackup, validateBackup } = await import('../src/services/backup.service.js?v=20260804-06');
setItem(STORAGE_KEYS.currentSession, { access_token: 'secret-access', refresh_token: 'secret-refresh' });
setItem(STORAGE_KEYS.users, [{ id: 'admin', password: 'secret-password' }]);
setItem(STORAGE_KEYS.userPermissionOverrides, { user: { 'data.export': 'allow' } });
setItem(STORAGE_KEYS.transactions, [{ id: 'sale', total: 10 }]);
setItem(STORAGE_KEYS.companySettings, { nomeFantasia: 'Loja' });
const serialized = createBackup();
const parsed = JSON.parse(serialized);
assert(!serialized.includes('secret'), 'backup must exclude credentials');
for (const key of [STORAGE_KEYS.currentSession, STORAGE_KEYS.users, STORAGE_KEYS.userPermissionOverrides]) assert(!Object.hasOwn(parsed.data, key));
setItem(STORAGE_KEYS.currentSession, { access_token: 'current-session' });
setItem(STORAGE_KEYS.transactions, []);
restoreBackup(serialized);
assert.equal(getItem(STORAGE_KEYS.transactions).length, 1);
assert.equal(getItem(STORAGE_KEYS.currentSession).access_token, 'current-session', 'restore must preserve current auth');
const tampered = JSON.parse(serialized);
tampered.data[STORAGE_KEYS.transactions] = [];
assert.throws(() => validateBackup(JSON.stringify(tampered)), /Checksum/);
globalThis.__PDV_RUNTIME_CONFIG__ = { dataProvider: 'supabase', supabaseUrl: 'https://example.test', supabaseAnonKey: 'public' };
assert.throws(() => restoreBackup(serialized), /local|online|Supabase/i, 'restore must refuse to replay historical data into production');
globalThis.__PDV_RUNTIME_CONFIG__ = { dataProvider: 'local' };
setItem(STORAGE_KEYS.transactions, [{ id: 'new-sale', total: 20 }]);
setItem(STORAGE_KEYS.companySettings, { nomeFantasia: 'Nova loja' });
const realSetItem = globalThis.localStorage.setItem;
globalThis.localStorage.setItem = (key, value) => {
  if (key === STORAGE_KEYS.companySettings && value.includes('"Loja"')) throw new Error('quota');
  return realSetItem(key, value);
};
assert.throws(() => restoreBackup(serialized), /revertida/);
globalThis.localStorage.setItem = realSetItem;
assert.equal(getItem(STORAGE_KEYS.transactions)[0].id, 'new-sale', 'partial restore must roll back earlier writes');
assert.equal(getItem(STORAGE_KEYS.currentSession).access_token, 'current-session');
setItem(STORAGE_KEYS.companySettings, { nested: { refresh_token: 'nested-secret' } });
assert.throws(() => createBackup(), /credencia|token|senha/i, 'nested credentials must not leak');
console.log('backup safety regression ok');
