import assert from 'node:assert/strict';
const store = new Map();
globalThis.localStorage = { getItem: key => store.get(key) ?? null, setItem: (key, value) => store.set(key, String(value)), removeItem: key => store.delete(key) };
const storage = await import('../src/services/storage.service.js?v=20260804-06');
const { STORAGE_KEYS } = await import('../src/database/schema.js?v=20260804-06');
const { setTestUserSession } = await import('./test-auth-fixture.mjs?v=20260804-06');
const { initSyncAppModule } = await import('../src/modules/sync-app/sync-app.module.js?v=20260804-06');
let click;
let downloaded = false;
let blob;
globalThis.document = { createElement: () => ({ click() { downloaded = true; }, remove() {} }), body: { append() {} } };
globalThis.URL.createObjectURL = value => { blob = value; return 'blob:backup'; };
globalThis.URL.revokeObjectURL = () => {};
const status = { textContent: '' };
const container = { innerHTML: '', querySelector: selector => selector.includes('status') ? status : { addEventListener: (event, callback) => { click = callback; } } };
setTestUserSession(storage, STORAGE_KEYS, { id: 'admin', name: 'Admin', role: 'admin', active: true });
initSyncAppModule(container);
assert.match(container.innerHTML, /Baixar backup/);
click();
assert(downloaded, 'authorized action must download operational JSON');
const backup = JSON.parse(await blob.text());
assert(!Object.hasOwn(backup.data, STORAGE_KEYS.currentSession));
setTestUserSession(storage, STORAGE_KEYS, { id: 'operator', name: 'Operador', role: 'operador', active: true });
downloaded = false;
click();
assert(!downloaded, 'permission must be checked again on action');
initSyncAppModule(container);
assert(!container.innerHTML.includes('data-backup-download'), 'operator must not receive backup button');
assert.match(container.innerHTML, /recupera/i, 'support must explain recovery');
console.log('support backup module ok');
